---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: ziedcloud2020
    password: ZiedCloud
    reauthorize: yes

- name: Tag and push to docker hub
  docker_image:
    name: ziedcloud2020/project-angular:latest
    repository: ziedcloud2020/project-angular
    tag: 7.0
    push: yes

