---

- name: output current user
  shell: |
    whoami; echo -en '\n'; groups $(whoami)
  register: cmd

- name: output current user  debug
  debug:
    msg: "{{ cmd['stdout_lines'] }}"

# tasks file for docker
- name: create image docker
  docker_image:
    name: ziedcloud2020/project-angular:latest
    build:
      path: "/var/lib/jenkins/workspace/project angular SCM"
      pull: no
    source: build
    state: present
    force_source: true
  

- name: run container docker
  docker_container:
    name: project-angular
    image: ziedcloud2020/project-angular:latest
    state: started
    recreate: true
    ports:
      - "4201:80"
  
